version: '2'
services:
  pg:
    image: postgres:10.7
    network_mode: host
    environment:
    - POSTGRES_DB=chimera
    - POSTGRES_PASSWORD=let-me-in
    command: >
      /usr/bin/env bash -c "docker-entrypoint.sh postgres &
        while true; do timeout 1 cat < /dev/null > /dev/tcp/localhost/5432 2>&1 ; if [ $$? = 0 ]; then break ; fi ; sleep 2 ; echo 'Database not ready!' ; done ; 
        echo 'xInitializing dCache database.' ;
        createuser -U postgres --no-superuser --no-createrole --createdb chimera ;
        createuser -U postgres --no-superuser --no-createrole --createdb dcache ;
        createdb -U dcache dcache ;
        createdb -O dcache -U postgres alarms ;
        createdb -O dcache -U postgres billing ;
        createdb -O dcache -U postgres pinmanager ;
        createdb -O dcache -U postgres spacemanager ;
        createdb -O dcache -U postgres transfermanagers ;
        createdb -O dcache -U postgres transfermanager ;
        createdb -O dcache -U postgres srm ;
        createdb -O dcache -U postgres replica ;
        createdb -O dcache -U postgres replicas ;
        echo 'dCache database initialized.' ;
        touch /monitor/postgres-ready ;
        sleep 400000 ;"
  dcache:
    image: onedata/dcache-docker
    network_mode: host
    build:
        context: .